// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGB_Project.Contexto;

#nullable disable

namespace SGB_Project.Migrations
{
    [DbContext(typeof(SGB_ProjectContext))]
    [Migration("20250707222000_RenameDataPrevistaDevolucaoColumn")]
    partial class RenameDataPrevistaDevolucaoColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SGB_Project.Models.Emprestimo", b =>
                {
                    b.Property<int>("IdEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdLeitor")
                        .HasColumnType("int");

                    b.HasKey("IdEmprestimo");

                    b.HasIndex("IdLeitor");

                    b.ToTable("Emprestimos");
                });

            // Rest of the model would go here
        }
    }
}
