// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGB_Project.Contexto;

#nullable disable

namespace SGB_Project.Migrations
{
    [DbContext(typeof(SGB_ProjectContext))]
    partial class SGB_ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SGB_Project.Models.Emprestimo", b =>
                {
                    b.Property<int>("IdEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdLeitor")
                        .HasColumnType("int");

                    b.HasKey("IdEmprestimo");

                    b.HasIndex("IdLeitor");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("SGB_Project.Models.EmprestimoItem", b =>
                {
                    b.Property<int>("IdEmprestimo")
                        .HasColumnType("int");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int");

                    b.HasKey("IdEmprestimo", "IdLivro");

                    b.HasIndex("IdLivro");

                    b.ToTable("EmprestimoItens");
                });

            modelBuilder.Entity("SGB_Project.Models.Leitor", b =>
                {
                    b.Property<int>("IdLeitor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLeitor");

                    b.ToTable("Leitores");
                });

            modelBuilder.Entity("SGB_Project.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLivro");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("SGB_Project.Models.Emprestimo", b =>
                {
                    b.HasOne("SGB_Project.Models.Leitor", "Leitor")
                        .WithMany()
                        .HasForeignKey("IdLeitor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leitor");
                });

            modelBuilder.Entity("SGB_Project.Models.EmprestimoItem", b =>
                {
                    b.HasOne("SGB_Project.Models.Emprestimo", "Emprestimo")
                        .WithMany("EmprestimoItens")
                        .HasForeignKey("IdEmprestimo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGB_Project.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprestimo");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("SGB_Project.Models.Emprestimo", b =>
                {
                    b.Navigation("EmprestimoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
